services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  WechatOfficialAccountCardBundle\Command\:
    resource: '../../Command/'
  WechatOfficialAccountCardBundle\Controller\:
    resource: '../../Controller/'
  WechatOfficialAccountCardBundle\EventListener\:
    resource: '../../EventListener/'
  WechatOfficialAccountCardBundle\Repository\:
    resource: '../../Repository/'
  WechatOfficialAccountCardBundle\Service\:
    resource: '../../Service/'
